### ISSUE TITLE
Error in rule make_identity_marginplot

### ISSUE THREAD

**Issue by yuanning-li** [conchoecia/odp#1]
Hey Darrin:

This is Li 😉. I got the odp installed, took me a little while but it is straightforward. I am running a test data (using the same genome as X and Y) just to make sure it is working. 

But I got an error in the pauvre step, not sure what is going on, do you mind taking a quick look at this?

`Error in rule make_identity_marginplot:
    jobid: 37
    output: synteny_analysis/plots/sample_similarity/ephydatia_and_rhopilema_peridentity_length.pdf
    shell:
        
        pauvre custommargin -i synteny_analysis/blastp_results/reciprocal_best/table_for_marginplot/ephydatia_and_rhopilema_peridentity_length.tsv --fileform pdf           --xcol MatchLength --ycol PercentIdentity           -o synteny_analysis/plots/sample_similarity/ephydatia_and_rhopilema_peridentity_length --no_timestamp           --plot_min_y 0 --plot_max_y 100           --plot_min_x 0 --plot_max_x 2000           -t "Protein Identity of ephydatia and rhopilema"
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)`

**Comment by yuanning-li** [comment]
I tracked down the log file and found this error:

"KeyError: 'text.latex.unicode is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'". 

I think this maybe related to the matplotlib version (I am using 3.4.1).  See this

"The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1."

**Comment by conchoecia** [comment]
I think I addressed this with https://github.com/conchoecia/pauvre/commit/a87f2c1c63a0542a1570d8999d2326e130017ffd. @yuanning-li, can you `pip update pauvre`, try again, then report back please? Thank you!

**Comment by conchoecia** [comment]
User reported that the most recent update fixed this.
