### ISSUE TITLE
'Workflow' object has no attribute 'cores' 

### ISSUE THREAD

**Issue by alexvasilikop** [conchoecia/odp#32]
Hello,

Thanks a lot for developing such useful tools. I am trying to run the snakemake pipeline for a couple of genomes and generate the macrosynteny plots.

```
 snakemake -r -p --snakefile scripts/odp
```

I get the following error that I suspect has to do sth with the snakemake version? (I am using v. 5.3)

```
AttributeError in line 221 of /odp/scripts/odp:
'Workflow' object has no attribute 'cores'
  File "/odp/scripts/odp", line 221, in <module>
```

Best 
Alex

**Comment by conchoecia** [comment]
Hi Alex,

To get around this for now, you must specify `--cores N` in your snakemake command. This is a good practice anyway, as snakemake by defaults to using all of the threads available on the machine you are using.

I will check to see what the default behavior is, and if I should instead add a more informative error message.

**Comment by alexvasilikop** [comment]
Great thanks, I think I have solved the issue.

best

**Comment by a-pontes** [comment]
Hello!
Thanks for developing this. I'm really excited to try it.
However I'm having the same issue. Tried what you proposed but it didn't work :/

here follows:

`snakemake -r -p --snakefile /data/yeastgenomics/Apps/odp/scripts/odp`

```
AttributeError in line 305 of /data/yeastgenomics/Apps/odp/scripts/odp:
'Workflow' object has no attribute 'cores'
  File "/data/yeastgenomics/Apps/odp/scripts/odp", line 305, in <module>
```
  
 and then tried:
 
` snakemake --cores 4 -r -p --snakefile /data/yeastgenomics/Apps/odp/scripts/odp`

but again...

```
AttributeError in line 305 of /data/yeastgenomics/Apps/odp/scripts/odp:
'Workflow' object has no attribute 'cores'
  File "/data/yeastgenomics/Apps/odp/scripts/odp", line 305, in <module>
```
  
Thanks!
Ana
