### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by amesclir** [conchoecia/odp#39]
I have found the next error when using odp. It seems to be something related with Wildcards and the number of colors.

snakemake --snakefile ./scripts/odp -c4
Building DAG of jobs...
InputFunctionException in rule hmm_against_prots in file /home/amesclir/local/bin/odp/scripts/odp, line 1824:
Error:
  IndexError: list index out of range
Wildcards:
  coloredby=BCnS_LGs
  sample=Crichardtii
Traceback:
  File "/home/amesclir/local/bin/odp/scripts/odp", line 1828, in <lambda>

**Comment by conchoecia** [comment]
Looks like you're trying to run the script in the install directory. Can you try again by running the program in a different directory? Can you also please post your config file?

**Comment by amesclir** [comment]
I have try to run it in a another folder, and I had the same error.
This is the config file
# this file is called config.yaml
ignore_autobreaks: True       # Skip steps to find breaks in synteny blocks
diamond_or_blastp: "diamond"  # "diamond" or "blastp"
plot_LGs: True                # Plot the ALGs based on the installed databases
plot_sp_sp: True              # Plot the synteny between two species, if False just generates .rbh files

species:
  Arabidopsisthaliana:
    proteins: /home/amesclir/local/bin/odp_run/genomes/Arabidopsisthaliana.fna
    chrom: /home/amesclir/local/bin/odp_run/genomes/Arabidopsisthaliana.chrom
    genome: /home/amesclir/local/bin/odp_run/genomes/Arabidopsisthaliana.faa
  Ceratopterisrichardtii:
    proteins: /home/amesclir/local/bin/odp_run/genomes/Ceratopterisrichardtii.fna
    chrom: /home/amesclir/local/bin/odp_run/genomes/Ceratopterisrichardtii.chrom
    genome: /home/amesclir/local/bin/odp_run/genomes/Ceratopterisrichardtii.faa

**Comment by changsarahl** [comment]
Hi, was this issue resolved? I have a similar issue with list index out or range

InputFunctionException in rule hmm_against_prots in file /home/krablab/odp/scripts/odp, line 1935:
Error:
  IndexError: list index out of range
Wildcards:
  coloredby=BCnS_LGs
  sample=Asap
Traceback:
  File "/home/krablab/odp/scripts/odp", line 1939, in <lambda>

**Comment by rachel1088** [comment]
> Looks like you're trying to run the script in the install directory. Can you try again by running the program in a different directory? Can you also please post your config file?

I also tried this and it didn't work. I'm having the same error.

Building DAG of jobs...
InputFunctionException in rule hmm_against_prots in file /mnt/ufs18/rs-028/Weed_lab/01_comparative_genomics/chenopod/odp/scripts/odp, line 1990:
Error:
  IndexError: list index out of range
Wildcards:
  coloredby=BCnS_LGs
  sample=Forsomanrum
Traceback:
  File "/chenopod/odp/scripts/odp", line 1994, in <lambda>

This is my config.yaml if that helps
ignore_autobreaks: True       # Skip steps to find breaks in synteny blocks
diamond_or_blastp: "diamond"  # "diamond" or "blastp"
plot_LGs: True                # Plot the ALGs based on the installed databases
plot_sp_sp: True              # Plot the synteny between two species, if False just generates .rbh files

species:
  Quinoa:
   proteins: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/Chenopodium_quinoa_cleaned_protein.fasta
   chrom: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/Chenopodium_quinoa1.chrom
   genome: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/Chenopodium_quinoa_cleaned.fasta
  Forsomanrum:
   proteins: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/CheFo_v2_cleaned_protein.fasta
   chrom: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/Chenopodium_Fo1.chrom
   genome: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/CheFo_v2_cleaned.fasta
  Album:
   proteins: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/Chenopodium_album_cleaned_protein.fasta
   chrom: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/Chenopodium_album1.chrom
   genome: /mnt/research/Weed_lab/01_comparative_genomics/chenopod/Chenopodium_album_cleaned.fasta
