### ISSUE TITLE
Error in rule plot_synteny_nocolor

### ISSUE THREAD

**Issue by yangzhou0916** [conchoecia/odp#46]
I have found the  error in plotting with odp using a simple dataset, which seems to be a problem with the font. Here is my config and log file.

config.yaml:
ignore_autobreaks: True       # Skip steps to find breaks in synteny blocks
diamond_or_blastp: "blastp"  # "diamond" or "blastp"
plot_LGs: True                # Plot the ALGs based on the installed databases
plot_sp_sp: True              # Plot the synteny between two species, if False just generates .rbh files

species:
  a:
    proteins: /home/user/odp/test/a.pep 
    chrom: /home/user/odp/test/a.chrom
    genome: /home/user/odp/test/a.fa
    minscafsize: 1000000  # Only plots scaffolds that are 1 Mbp or longer
  b:
    proteins: /home/user/odp/test/b.pep
    chrom: /home/user/odp/test/b.chrom
    genome: /home/user/odp/test/b.fa
    minscafsize: 1000000  # Only plots scaffolds that are 1 Mbp or larger

log:

/home/user/odp/scripts/odp:1087: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.  # parse the colorset
QXcbConnection: Failed to initialize XRandr
Error in rule plot_synteny_nocolor:    jobid: 0
    input: odp/step1-rbh/b_a_reciprocal_best_hits.D.FET.rbh, odp/step0-chromsize/analyses/b_a.chromsize
    output: odp/step2-figures/synteny_nocolor/b1_a_xy_reciprocal_best_hits.plotted.rbh, odp/step2-figures/synteny_nocolor/b_a_xy_synteny.pdf, odp/step2-figures/synteny_n
ocolor/b_a_yx_synteny.pdf

RuleException:
TTLibError in file /home/user/odp/scripts/odp, line 1637:
not enough 'glyf' table data

**Comment by stsmall** [comment]
@yangzhou0916 
I am having the same error, how did you solve this?
