### ISSUE TITLE
Start and Stop in GFF to Chrom file

### ISSUE THREAD

**Issue by keith-harrison** [conchoecia/odp#48]
Hey just asking if the start and stop are meant to be 
```
       start = int(splitd[3])
        stop = int(splitd[3])
```
in the NCBIGFF2CHROM python file?
line 30/31

**Comment by conchoecia** [comment]
Yes, thank you. It should mostly be inconsequential at the moment as I only use a single point coordinate for the genes, but this will be fixed in a future release.

**Comment by conchoecia** [comment]
Still not doing anything with the stop positions. Closing for now as this doesn't affect the current implementation.
