### ISSUE TITLE
ValueError in file /odp/scripts/odp, line 598: No objects to concatenate

### ISSUE THREAD

**Issue by ask-krishnan** [conchoecia/odp#51]
Hi, I'm repeatedly getting this issue — I saw that a previous issue on the repository also involved this bug, would it be an issue with the genome assembly that I'm analyzing? What might I need to fix to make it work? (I've shorted some of the paths in the error log to make it more interpretable)

Would really appreciate any help with this issue — thank you so much! 

```
Error in rule species_HMM_D_and_FET:
    jobid: 0
    input: odp/step1-rbh/UnicellMetazoanLgs_Bminutum_reciprocal_best_hits.hmm.rbh, odp/step0-chromsize/species/Bminutum.chromsize
    output: odp/step1-rbh/UnicellMetazoanLgs_Bminutum_reciprocal_best_hits.hmm.D.FET.rbh

RuleException:
ValueError in file /odp/scripts/odp, line 598:
No objects to concatenate
  File "/odp/scripts/odp", line 1883, in __rule_species_HMM_D_and_FET
  File "/odp/scripts/odp", line 598, in calc_D_for_y_and_x
  File "/users/ak4890/bin/miniconda3/envs/odp_new/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 372, in concat
  File "/users/ak4890/bin/miniconda3/envs/odp_new/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 429, in __init__
  File "/users/ak4890/bin/miniconda3/envs/odp_new/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
[Sun Jul 30 16:33:32 2023]
Finished job 24.
21 of 50 steps (42%) done
[Sun Jul 30 19:51:30 2023]
Finished job 20.
22 of 50 steps (44%) done
```

**Comment by conchoecia** [comment]
Hi Krishnan - I've only ever seen this error when using genomes that are not chromosome-scale, but maybe it is something else. This crops up when there are no scaffolds with more genes than the window size for the D-calculation function. Do you think that the genome quality might be an issue, or are all of the genomes you're using chromosome-scale?

**Comment by conchoecia** [comment]
@ask-krishnan - should now be resolved in https://github.com/conchoecia/odp/commit/ba6c45375c2bf5e75a9ff0779e5d75b5509209db

Please run `git pull`, then try again. Please reopen this issue if you face the same issue, or a new issue if something else comes up.
