### ISSUE TITLE
Runtime for odp_rbh_to_alignments when building new ALGs

### ISSUE THREAD

**Issue by cvargas88** [conchoecia/odp#52]
Dear Darrin, 
Thank you for developing such an useful tool. I have been running the odp_rbh_to_alignments script using snakemake to build new ALGs for the species I am using. The command is the following: "snakemake -r -p --snakefile odp/scripts/odp_rbh_to_alignments --cores 15" and while I provide 15 threads only one is being used. With only 1 thread the run time is estimated to be of a couple of months. However, when running odp all of the threads were used. Is there some parameter that needs to be tuned in the odp_rbh_to_alignments script? I tried changing the threads parameter from 1 to 14 in every place in the script but it still uses only a single thread. What should I do?
Thanks a lot!

**Comment by conchoecia** [comment]
Hi - at which step was it running all the threads instead of the 15 you specified? Can you post screenshots of htop perhaps?

**Comment by cvargas88** [comment]
Hi Darrin, thank you for your reply. I believe it was an issue with the installation. I did a fresh installation using the latest version and finally I was able to run odp_rbh_to_alignments using the available threads that I specified. Thanks a lot!

**Comment by conchoecia** [comment]
Closing - please reopen if you encounter something related to this issue again.
