### ISSUE TITLE
Analysis of data with a large number of duplicates

### ISSUE THREAD

**Issue by maxnest** [conchoecia/odp#62]
Dear colleagues,
Thank you for developing such a useful tool. Unfortunately, in my case the pipeline stops with an error stating that the fasta files with proteins contain duplicated sequences. I see two options as possible solutions: 1) clustering similar sequences using CDHIT and including only 1 representative sequence from each cluster in the analysis, or 2) parsing the results of orthologues searches (OrthoFinder output tables) and then selecting 1 protein per species from each orthogroups. However, in any case, such a reduction in information redundancy will affect the study of data, because we exclude gene duplications from consideration. Given presence of duplications, could you please tell what strategy for analyzing data with many identical proteins would you recommend? Should I specify “best” as a value for a “duplicate_proteins” parameter in the config file?
I would appreciate any advice.
Best regards,
Maksim

**Comment by conchoecia** [comment]
Our pipeline does not currently have any special considerations to account for the history of WGD events. For a quick solution that will allow you move forward to check for homology, please see this comment: https://github.com/conchoecia/odp/issues/49#issuecomment-1653524983

**Comment by conchoecia** [comment]
Closing - please reopen if you have questions or suggestions about duplicate handling
